import puppeteer from 'puppeteer-core';
import fs from 'fs';
const S = process.argv[2];
const iwer = fs.readFileSync(S + '/iwer/iwer.min.js', 'utf8');
const b = await puppeteer.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: 'new', args: ['--use-angle=d3d11', '--enable-gpu', '--ignore-gpu-blocklist'] });
const p = await b.newPage();
await p.setViewport({ width: 1280, height: 720 });
const logs = [];
p.on('console', m => logs.push(m.type() + ': ' + m.text().slice(0, 300)));
p.on('pageerror', e => logs.push('pageerror: ' + e.message));
await p.evaluateOnNewDocument(iwer + `;(function(){ const d = new IWER.XRDevice(IWER.metaQuest3); d.installRuntime({ forceInstall: true }); window.__iwer = d; })();`);
await p.goto('http://localhost:5304/', { waitUntil: 'load' });
await p.waitForFunction(() => document.getElementById('boot')?.classList.contains('gone'), { timeout: 90000 });
console.log('ua', await p.evaluate(() => navigator.userAgent));
console.log('supported', await p.evaluate(() => navigator.xr.isSessionSupported('immersive-vr')));
console.log('binding', await p.evaluate(() => typeof XRWebGLBinding !== 'undefined' && 'createProjectionLayer' in XRWebGLBinding.prototype));
// a button gives the page a user gesture
await p.evaluate(() => { const b = document.createElement('button'); b.id = 'xrgo'; b.textContent = 'go'; Object.assign(b.style, { position: 'fixed', left: '0', top: '0', zIndex: 9999 }); document.body.append(b);
  b.onclick = async () => { try { const g = window.droneon.game; const r = g.renderer; r.xr.enabled = true; r.xr.setReferenceSpaceType('local-floor');
    const s = await navigator.xr.requestSession('immersive-vr', { optionalFeatures: ['local-floor', 'bounded-floor', 'layers'] });
    await r.xr.setSession(s); window.__s = s; const cam = new window.THREE.PerspectiveCamera(); const rig = new window.THREE.Group(); rig.position.set(0, 0.3, 12); rig.add(cam); g.world.scene.add(rig);
    let n = 0; r.setAnimationLoop(() => { n++; window.__n = n; r.render(g.world.scene, cam); }); } catch (e) { console.error('xr fail', e.message, e.stack); } }; });
await p.click('#xrgo');
await new Promise(r => setTimeout(r, 4000));
console.log('frames', await p.evaluate(() => window.__n), 'presenting', await p.evaluate(() => window.droneon.game.renderer.xr.isPresenting));
console.log('canvas', await p.evaluate(() => { const c = document.getElementById('gl'); return { w: c.width, h: c.height, parent: c.parentElement?.tagName + '.' + c.parentElement?.className, style: c.style.cssText.slice(0, 200) }; }));
await p.screenshot({ path: S + '/probe_xr.png' });
await p.evaluate(() => window.__s.end());
await new Promise(r => setTimeout(r, 1000));
console.log('after end presenting', await p.evaluate(() => window.droneon.game.renderer.xr.isPresenting));
console.log(logs.filter(l => !l.includes('X4122')).slice(0, 40).join('\n'));
await b.close();
